homeassistant:
  name: Home
  latitude: 30.580100000000002
  longitude: 114.2734
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include customize.yaml

default_config:

sensor:
  - platform: iio_dht
    scan_interval: 150

switch:
  - platform: direct_gpio
    name: GPIO26
    port: 26
    inverted: false

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homekit:

frontend:

config:

logbook:

recorder:
  purge_interval: 1
  purge_keep_days: 3
  db_url: sqlite:////tmp/home-assistant.db
  exclude:
    domains:
      - automation
    entities:
      - sun.sun

