homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include customize.yaml
  # to be removed in the future
  auth_providers:
    - type: legacy_api_password

http:
  api_password: !secret http_password

default_config:

sensor:
  - platform: iio_dht
    scan_interval: 150

switch:
  - platform: direct_gpio
    name: GPIO26
    port: 26
    inverted: false

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homekit:

frontend:
  themes: !include themes.yaml

config:

logbook:

recorder:
  purge_interval: 1
  purge_keep_days: 3
  db_url: sqlite:////tmp/home-assistant.db
  exclude:
    domains:
      - automation
      - group
      - device_tracker
      - persistent_notification
      - zone
    entities:
      - sun.sun

ios:

