homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include include/customize.yaml

sensor: !include include/sensors.yaml 
light: !include include/lights.yaml 
switch: !include include/switches.yaml 
group: !include include/groups.yaml
automation: !include include/automations.yaml
python_script:
script: !include include/scripts.yaml 
homekit: 
frontend: !include include/frontend.yaml
config: 
logbook: 
history:
recorder: !include include/recorder.yaml
mqtt: !include include/mqtt.yaml
system_health:
logger:
  default: info

bark:
  url: !secret bark_url

