- alias: 'toggle the lamp through mqtt'
  initial_state: true
  trigger:
    platform: mqtt
    topic: hass/dorm/desk/lamp/toggle
  action:
    service: light.toggle
    entity_id: light.desktop_lamp

- alias: 'notify me at startup'
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: bark.bark
    data:
      title: "Home Assistant"
      message: "Guten Tag!"

- alias: 'notify admins'
  initial_state: true
  trigger:
    platform: mqtt
    topic: /hass/util/admin/notify
  action:
    service: bark.bark
    data_template:
      title: "Home Assistant"
      message: "{{ trigger.payload }}"

- alias: 'go to bed'
  initial_state: true
  trigger: 
    platform: time
    at: '23:00:00'
  action:
    service: script.blink_the_lamp

