- alias: 'toggle the lamp through mqtt'
  initial_state: true
  trigger:
    platform: mqtt
    topic: hass/dorm/desk/lamp/toggle
  action:
    service: light.toggle
    entity_id: light.desktop_lamp

- alias: 'notify me at startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: bark.bark
    data:
      title: "Home Assistant"
      message: "Guten Tag!"

