#- platform: iio_dht
#  scan_interval: 150

- platform: systemmonitor
  scan_interval: 15
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /

- platform: uptime
  name: HASS Uptime
  unit_of_measurement: hours

- platform: command_line
  command: "uptime | sed 's/.*up\\s*//' | sed 's/,\\s\\+load.*//'"
  name: System Uptime

- platform: command_line
  command: "uptime | sed 's/.*average://'"
  name: System Load

- platform: MAX44009
  scan_interval: 30

- platform: SHT31
  scan_interval: 120

- platform: mqtt
  name: "remain_power"
  state_topic: "hass/dorm/power"
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.remain }}"

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ '%0.1f' | format(value | float | multiply(0.001)) }}"

