#- platform: iio_dht
#  scan_interval: 150

- platform: systemmonitor
  scan_interval: 15
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
- platform: template
  sensors:
    fmt_processor_use:
      friendly_name: "CPU"
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.processor_use') | round }}"
    fmt_memory_use_percent:
      friendly_name: "Memory"
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.memory_use_percent') | round}}"
    fmt_disk_use_percent:
      friendly_name: "Disk"
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.disk_use_percent') | round }}"

- platform: uptime
  name: Raw HASS Uptime
  unit_of_measurement: hours
- platform: template
  sensors: 
    hass_uptime:
      friendly_name: "HASS Uptime"
      unit_of_measurement: hours
      value_template: "{{ '%0.1f' | format(states('sensor.raw_hass_uptime') | float) }}"

- platform: command_line
  command: "cat /proc/uptime"
  name: System Uptime
  value_template: "{{ '%0.1f hours' | format(float(value.split(' ')[0])/3600 | round(1)) }}"

- platform: command_line
  command: "uptime | sed 's/.*average://'"
  name: System Load

- platform: MAX44009
  scan_interval: 30

- platform: SHT31
  scan_interval: 120

- platform: mqtt
  name: "remain_power"
  state_topic: "hass/dorm/power"
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.remain }}"

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ '%0.1f' | format(value | float | multiply(0.001)) }}"

- platform: bandwagonhost
  veid: !secret bwh_veid
  api_key: !secret bwh_api
  monitored_conditions:
    - VPS_STATE
    - CURRENT_BANDWIDTH_USED
    - RAM_USED
    - DISK_USED
    - SWAP_USED

