- platform: systemmonitor
  scan_interval: 15
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /

- platform: uptime
  name: HASS Uptime
  unit_of_measurement: hours

- platform: command_line
  command: "cat /proc/uptime"
  name: System Uptime
  value_template: "{{ '%0.1f hours' | format(float(value.split(' ')[0])/3600 | round(1)) }}"

- platform: command_line
  command: "uptime | sed 's/.*average://'"
  name: System Load

#- platform: MAX44009
  #scan_interval: 30
  #name: "desktop luminous"
  #addr0: 0

#- platform: SHT31
  #scan_interval: 120
  #sensors:
    #temperature:
      #name: desktop temperature
    #humidity:
      #name: desktop humidity

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ '%0.1f' | format(value | float | multiply(0.001)) }}"

- platform: command_line
  name: latest HA version
  scan_interval: 86400
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"

- platform: version
  name: current HA version

- platform: sht31
  name: bedroom
  i2c_address: 0x44

